import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { createRemoteJWKSet, jwtVerify } from 'https://esm.sh/jose@5.10.0';
const ISSUER='https://oidc.vercel.com/ahmetrz1';const AUDIENCE='https://vercel.com/ahmetrz1';
const JWKS=createRemoteJWKSet(new URL('https://oidc.vercel.com/ahmetrz1/.well-known/jwks'));
const enc=new TextEncoder();
async function sha256(text:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(text));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function gzipBytes(text:string){const s=new Blob([text]).stream().pipeThrough(new CompressionStream('gzip'));return new Uint8Array(await new Response(s).arrayBuffer());}
async function verify(req:Request){const h=req.headers.get('authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)throw new Error('missing_token');const {payload}=await jwtVerify(token,JWKS,{issuer:ISSUER,audience:AUDIENCE});if(payload.owner_id!=='team_cwoMCRfpsJ3r1ouSJFoOagbW'||payload.project!=='skillset-v1-bridge'||payload.environment!=='production')throw new Error('claims_rejected');return payload;}
Deno.serve(async(req)=>{try{const claims=await verify(req);const su=Deno.env.get('SUPABASE_URL'),sk=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!su||!sk)return new Response('config',{status:500});const db=createClient(su,sk,{auth:{persistSession:false}});const body=await req.json();
 if(body?.kind==='probe'){await db.rpc('skillset_set_state',{p_key:'v1:bridge-probe',p_value:{ok:true,project:claims.project,project_id:claims.project_id,environment:claims.environment,owner:claims.owner,at:new Date().toISOString()}});return Response.json({ok:true,kind:'probe'});}
 if(body?.kind==='listing'){const p=body.payload??{},rows=Array.isArray(p.data)?p.data:[];if(rows.length>500)throw new Error('listing_too_large');const pag=p.pagination??{};const {data:count,error}=await db.rpc('skillset_seed_v1_page',{p_rows:rows,p_page:Number(pag.page??0),p_per_page:Number(pag.perPage??rows.length),p_total:Number(pag.total??0),p_has_more:Boolean(pag.hasMore)});if(error)throw new Error(`seed:${error.message}`);return Response.json({ok:true,kind:'listing',rows:rows.length,upserted:Number(count??0)});}
 if(body?.kind==='claim-detail'){const limit=Math.max(1,Math.min(Number(body.limit??250),300));const {data,error}=await db.rpc('skillset_claim_v1_detail_jobs',{p_limit:limit});if(error)throw new Error(`claim:${error.message}`);return Response.json({ok:true,jobs:(data??[]).map((x:any)=>String(x.id))});}
 if(body?.kind==='detail-error'){const id=String(body.id??'');if(!id)throw new Error('missing_id');const {error}=await db.rpc('skillset_mark_v1_error',{p_id:id,p_error:String(body.error??'v1_error'),p_status:body.status===undefined?null:Number(body.status)});if(error)throw new Error(`mark:${error.message}`);return Response.json({ok:true,kind:'detail-error',id});}
 if(body?.kind==='detail'){const d=body.payload??{},id=String(d.id??'');if(!id)throw new Error('missing_id');const files=Array.isArray(d.files)?d.files:[];const f=files.find((x:any)=>x?.path==='SKILL.md'&&typeof x?.contents==='string')??files.find((x:any)=>typeof x?.path==='string'&&x.path.endsWith('/SKILL.md')&&typeof x?.contents==='string');if(!f)throw new Error('skill_md_missing');const text=String(f.contents),hash=await sha256(text),gz=await gzipBytes(text),key=`sha256/${hash.slice(0,2)}/${hash}.md.gz`;const {error:upErr}=await db.storage.from('skillset-corpus').upload(key,gz,{contentType:'application/gzip',upsert:false,cacheControl:'31536000'});if(upErr&&!/already|duplicate/i.test(String(upErr.message)))throw new Error(`upload:${upErr.message}`);const {error:se}=await db.rpc('skillset_store_object_content',{p_id:id,p_content_sha256:hash,p_content_bytes:enc.encode(text).byteLength,p_object_key:key,p_compressed_bytes:gz.byteLength,p_source_url:`https://skills.sh/${id}`,p_backend:'supabase-storage'});if(se)throw new Error(`store:${se.message}`);await db.rpc('skillset_mark_v1_success',{p_id:id});return Response.json({ok:true,kind:'detail',id,hash,bytes:enc.encode(text).byteLength});}
 return new Response('bad_kind',{status:400});
}catch(e){const m=e instanceof Error?e.message:String(e);return Response.json({ok:false,error:m},{status:401});}});