create schema if not exists skillset;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

create table if not exists skillset.skills (
  id text primary key,
  source text,
  skill_name text,
  description text,
  owner text,
  repo text,
  skill_url text,
  source_url text,
  installs bigint,
  skill_md text,
  content_sha256 text,
  content_bytes integer,
  retrieval_status text not null default 'pending',
  retrieval_error text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  retrieved_at timestamptz,
  updated_at timestamptz not null default now(),
  content_object_key text,
  content_encoding text,
  compressed_bytes integer,
  storage_backend text
);

create table if not exists skillset.crawl_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists skillset.repositories (
  source text primary key,
  owner text not null,
  repo text not null,
  discovery_status text not null default 'pending',
  default_branch text,
  discovered_skill_files integer not null default 0,
  new_skills_found integer not null default 0,
  attempts integer not null default 0,
  last_error text,
  last_scanned_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists skillset.owner_search (
  owner text primary key,
  status text not null default 'pending',
  result_count integer,
  saturated boolean not null default false,
  attempts integer not null default 0,
  last_error text,
  searched_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists skillset.job_tokens (
  token uuid primary key,
  purpose text not null,
  expires_at timestamptz not null default (now()+interval '10 minutes'),
  used_at timestamptz
);

create table if not exists skillset.discovery_queue (
  id bigint generated by default as identity primary key,
  kind text not null,
  value text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(kind,value)
);

create index if not exists skills_retrieval_status_idx on skillset.skills(retrieval_status);
create index if not exists skills_owner_idx on skillset.skills(owner);
create index if not exists skills_repo_idx on skillset.skills(repo);
create index if not exists idx_skillset_content_hash on skillset.skills(content_sha256);
create index if not exists idx_skillset_object_key on skillset.skills(content_object_key);
create index if not exists discovery_queue_status_idx on skillset.discovery_queue(status,id);

create or replace function public.skillset_consume_job_token(p_token text,p_purpose text)
returns boolean language plpgsql security definer set search_path to 'public','skillset' as $function$
declare v_token uuid;v_count integer:=0;begin
 begin v_token:=p_token::uuid; exception when others then return false; end;
 update skillset.job_tokens set used_at=now() where token=v_token and purpose=p_purpose and used_at is null and expires_at>now();
 get diagnostics v_count=row_count;return v_count=1;
end;$function$;

create or replace function public.skillset_bulk_seed(p_rows jsonb)
returns integer language plpgsql security definer set search_path to 'public','skillset' as $function$
declare v_count integer;begin
 with normalized as (
  select coalesce(r->>'id',concat_ws('/',r->>'source',r->>'skillId')) id,r->>'source' source,
         coalesce(r->>'name',r->>'skillId') skill_name,r->>'owner' owner,r->>'repo' repo,
         coalesce(r->>'skill_url','https://skills.sh/'||(r->>'source')||'/'||(r->>'skillId')) skill_url,
         coalesce(r->>'source_url',r->>'githubUrl') source_url,coalesce((r->>'installs')::bigint,0) installs
  from jsonb_array_elements(p_rows) r where coalesce(r->>'source','')<>'' and coalesce(r->>'skillId','')<>''
 ),deduped as (select distinct on(id)* from normalized order by id,installs desc)
 insert into skillset.skills(id,source,skill_name,owner,repo,skill_url,source_url,installs,retrieval_status,first_seen_at,last_seen_at,updated_at)
 select id,source,skill_name,owner,repo,skill_url,source_url,installs,'pending',now(),now(),now() from deduped
 on conflict(id) do update set installs=greatest(coalesce(skillset.skills.installs,0),excluded.installs),source_url=coalesce(excluded.source_url,skillset.skills.source_url),last_seen_at=now(),updated_at=now();
 get diagnostics v_count=row_count;
 insert into skillset.repositories(source,owner,repo)
 select distinct r->>'source',coalesce(r->>'owner',split_part(r->>'source','/',1)),coalesce(r->>'repo',split_part(r->>'source','/',2))
 from jsonb_array_elements(p_rows) r where coalesce(r->>'source','') like '%/%' on conflict(source) do nothing;
 insert into skillset.owner_search(owner)
 select distinct coalesce(r->>'owner',split_part(r->>'source','/',1)) from jsonb_array_elements(p_rows) r where coalesce(r->>'source','') like '%/%' on conflict(owner) do nothing;
 return v_count;
end;$function$;

create or replace function public.skillset_seed_status(p_source text,p_total integer,p_processed integer,p_status text)
returns void language sql security definer set search_path to 'public','skillset' as $function$
 insert into skillset.crawl_state(key,value,updated_at) values('seed:'||p_source,jsonb_build_object('source',p_source,'total',p_total,'processed',p_processed,'status',p_status),now())
 on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at;
$function$;

create or replace function public.skillset_claim_pending(p_limit integer default 50)
returns table(id text,source text,skill_name text,repo text) language plpgsql security definer set search_path to 'skillset','public' as $function$
begin return query
 with picked as (select s.id from skillset.skills s where s.retrieval_status in ('pending','retry') or (s.retrieval_status='processing' and s.updated_at<now()-interval '15 minutes') order by s.first_seen_at,s.id for update skip locked limit greatest(1,least(p_limit,100))),
 claimed as (update skillset.skills s set retrieval_status='processing',updated_at=now() from picked p where s.id=p.id returning s.id,s.source,s.skill_name,s.repo)
 select * from claimed;end;$function$;

create or replace function public.skillset_store_object_content(p_id text,p_content_sha256 text,p_content_bytes integer,p_object_key text,p_compressed_bytes integer,p_source_url text default null,p_backend text default 'supabase-storage')
returns void language plpgsql security definer set search_path to 'skillset','public' as $function$
begin update skillset.skills set skill_md=null,content_sha256=p_content_sha256,content_bytes=p_content_bytes,content_object_key=p_object_key,content_encoding='gzip',compressed_bytes=p_compressed_bytes,storage_backend=p_backend,source_url=coalesce(p_source_url,source_url),retrieval_status='ok',retrieval_error=null,retrieved_at=now(),updated_at=now() where id=p_id;end;$function$;

create or replace function public.skillset_mark_error(p_id text,p_error text)
returns void language plpgsql security definer set search_path to 'skillset','public' as $function$
begin update skillset.skills set retrieval_status='retry',retrieval_error=left(p_error,2000),updated_at=now() where id=p_id;end;$function$;

create or replace function public.skillset_next_unmigrated_hashes(p_limit integer default 100)
returns table(content_sha256 text,skill_md text,content_bytes integer) language sql security definer set search_path to 'skillset','public' as $function$
 select distinct on(s.content_sha256) s.content_sha256,s.skill_md,s.content_bytes from skillset.skills s where s.retrieval_status='ok' and s.skill_md is not null and s.content_sha256 is not null and s.content_object_key is null order by s.content_sha256 limit greatest(1,least(p_limit,250));
$function$;

create or replace function public.skillset_mark_object_stored(p_sha text,p_object_key text,p_compressed_bytes integer,p_backend text default 'supabase-storage')
returns integer language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_count integer;begin update skillset.skills set content_object_key=p_object_key,content_encoding='gzip',compressed_bytes=p_compressed_bytes,storage_backend=p_backend,skill_md=null,updated_at=now() where content_sha256=p_sha and retrieval_status='ok';get diagnostics v_count=row_count;return v_count;end;$function$;

create or replace function public.skillset_estimated_storage_bytes()
returns bigint language sql security definer set search_path to 'skillset','public' as $function$
 select coalesce(sum(x.compressed_bytes),0)::bigint from (select distinct on(content_object_key) content_object_key,compressed_bytes from skillset.skills where content_object_key is not null and compressed_bytes is not null order by content_object_key) x;
$function$;
create or replace function public.skillset_storage_has_capacity(p_limit_bytes bigint default 850000000)
returns boolean language sql security definer set search_path to 'public','skillset' as $function$ select public.skillset_estimated_storage_bytes()<p_limit_bytes;$function$;

create or replace function public.skillset_claim_repository()
returns table(source text,owner text,repo text) language plpgsql security definer set search_path to 'skillset','public' as $function$
begin return query with picked as (select r.source from skillset.repositories r where r.discovery_status in ('pending','retry') or (r.discovery_status='processing' and r.updated_at<now()-interval '20 minutes') order by r.attempts,r.source for update skip locked limit 1),claimed as (update skillset.repositories r set discovery_status='processing',attempts=attempts+1,updated_at=now() from picked p where r.source=p.source returning r.source,r.owner,r.repo) select * from claimed;end;$function$;

create or replace function public.skillset_finish_repository(p_source text,p_branch text,p_files integer,p_new integer,p_error text default null)
returns void language plpgsql security definer set search_path to 'skillset','public' as $function$
begin update skillset.repositories set discovery_status=case when p_error is null then 'ok' when attempts>=3 then 'failed' else 'retry' end,default_branch=coalesce(p_branch,default_branch),discovered_skill_files=greatest(discovered_skill_files,coalesce(p_files,0)),new_skills_found=new_skills_found+coalesce(p_new,0),last_error=p_error,last_scanned_at=now(),updated_at=now() where source=p_source;end;$function$;

create or replace function public.skillset_upsert_repo_discovered_skill(p_source text,p_skill_name text,p_repo_path text,p_owner text,p_repo text,p_source_url text,p_sha text,p_raw_bytes integer,p_object_key text,p_gzip_bytes integer)
returns boolean language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_id text;v_inserted boolean;begin
 select s.id into v_id from skillset.skills s where s.source=p_source and lower(s.skill_name)=lower(p_skill_name) order by case when s.id=p_source||'/'||p_skill_name then 0 else 1 end,s.first_seen_at limit 1;
 if v_id is null then v_id:=p_source||'/@repo/'||trim(both '/' from p_repo_path);end if;
 insert into skillset.skills(id,source,skill_name,owner,repo,source_url,installs,content_sha256,content_bytes,content_object_key,content_encoding,compressed_bytes,storage_backend,retrieval_status,first_seen_at,last_seen_at,retrieved_at,updated_at)
 values(v_id,p_source,p_skill_name,p_owner,p_repo,p_source_url,0,p_sha,p_raw_bytes,p_object_key,'gzip',p_gzip_bytes,'supabase-storage','ok',now(),now(),now(),now())
 on conflict(id) do update set content_sha256=excluded.content_sha256,content_bytes=excluded.content_bytes,content_object_key=excluded.content_object_key,content_encoding='gzip',compressed_bytes=excluded.compressed_bytes,storage_backend='supabase-storage',source_url=excluded.source_url,retrieval_status='ok',retrieval_error=null,last_seen_at=now(),retrieved_at=now(),updated_at=now()
 returning (xmax=0) into v_inserted;return v_inserted;end;$function$;

create or replace function public.skillset_claim_leaderboard_page()
returns integer language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_state jsonb;v_page integer;begin
 select value into v_state from skillset.crawl_state where key='leaderboard:all-time' for update;
 if v_state is null then v_state:='{"nextPage":0,"status":"pending"}'::jsonb;insert into skillset.crawl_state(key,value) values('leaderboard:all-time',v_state);end if;
 if coalesce(v_state->>'status','')='complete' then return null;end if;
 if coalesce((v_state->>'inProgress')::boolean,false) and coalesce((v_state->>'claimedAt')::timestamptz,now()-interval '1 hour')>now()-interval '5 minutes' then return null;end if;
 v_page:=coalesce((v_state->>'nextPage')::integer,0);v_state:=jsonb_set(jsonb_set(v_state,'{inProgress}','true'::jsonb),'{claimedAt}',to_jsonb(now()));update skillset.crawl_state set value=v_state,updated_at=now() where key='leaderboard:all-time';return v_page;end;$function$;

create or replace function public.skillset_seed_leaderboard_page(p_rows jsonb,p_page integer,p_total integer,p_has_more boolean)
returns integer language plpgsql security definer set search_path to 'public','skillset' as $function$
declare v_count integer;begin
 with n as (select concat_ws('/',r->>'source',r->>'skillId') id,r->>'source' source,coalesce(r->>'name',r->>'skillId') skill_name,coalesce((r->>'installs')::bigint,0) installs from jsonb_array_elements(p_rows) r where coalesce(r->>'source','')<>'' and coalesce(r->>'skillId','')<>''),d as (select distinct on(id)* from n order by id,installs desc)
 insert into skillset.skills(id,source,skill_name,owner,repo,skill_url,source_url,installs,retrieval_status,first_seen_at,last_seen_at,updated_at)
 select id,source,skill_name,case when source like '%/%' then split_part(source,'/',1) end,case when source like '%/%' then split_part(source,'/',2) end,'https://skills.sh/'||id,case when source like '%/%' then 'https://github.com/'||source end,installs,'pending',now(),now(),now() from d
 on conflict(id) do update set installs=excluded.installs,last_seen_at=now(),updated_at=now();get diagnostics v_count=row_count;
 insert into skillset.repositories(source,owner,repo) select distinct r->>'source',split_part(r->>'source','/',1),split_part(r->>'source','/',2) from jsonb_array_elements(p_rows) r where coalesce(r->>'source','') like '%/%' on conflict(source) do nothing;
 insert into skillset.owner_search(owner) select distinct split_part(r->>'source','/',1) from jsonb_array_elements(p_rows) r where coalesce(r->>'source','') like '%/%' on conflict(owner) do nothing;
 insert into skillset.crawl_state(key,value,updated_at) values('leaderboard:all-time',jsonb_build_object('page',p_page,'nextPage',p_page+1,'total',p_total,'hasMore',p_has_more,'status',case when p_has_more then 'running' else 'complete' end,'inProgress',false),now()) on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at;return v_count;end;$function$;

create or replace function public.skillset_fail_leaderboard_page(p_page integer,p_error text)
returns void language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_state jsonb;begin select value into v_state from skillset.crawl_state where key='leaderboard:all-time' for update;if coalesce((v_state->>'nextPage')::integer,-1)=p_page then v_state:=jsonb_set(jsonb_set(v_state,'{inProgress}','false'::jsonb),'{lastError}',to_jsonb(left(p_error,500)));update skillset.crawl_state set value=v_state,updated_at=now() where key='leaderboard:all-time';end if;end;$function$;

create or replace function public.skillset_claim_owner_search()
returns text language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_owner text;begin select o.owner into v_owner from skillset.owner_search o where o.status in ('pending','retry') or (o.status='processing' and o.updated_at<now()-interval '10 minutes') order by o.attempts,o.owner for update skip locked limit 1;if v_owner is null then return null;end if;update skillset.owner_search set status='processing',attempts=attempts+1,updated_at=now() where owner=v_owner;return v_owner;end;$function$;

create or replace function public.skillset_finish_owner_search(p_owner text,p_count integer,p_error text default null)
returns void language plpgsql security definer set search_path to 'skillset','public' as $function$
begin update skillset.owner_search set status=case when p_error is null then 'ok' when attempts>=3 then 'failed' else 'retry' end,result_count=p_count,saturated=coalesce(p_count,0)>=200,last_error=p_error,searched_at=now(),updated_at=now() where owner=p_owner;end;$function$;

create or replace function public.skillset_seed_search_results(p_rows jsonb)
returns integer language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_count integer;begin
 with n as (select coalesce(r->>'id',concat_ws('/',r->>'source',r->>'skillId')) id,r->>'source' source,coalesce(r->>'name',r->>'skillId') skill_name,coalesce((r->>'installs')::bigint,0) installs from jsonb_array_elements(p_rows) r where coalesce(r->>'source','')<>'' and coalesce(r->>'skillId',r->>'name','')<>''),d as (select distinct on(id)* from n order by id,installs desc)
 insert into skillset.skills(id,source,skill_name,owner,repo,skill_url,source_url,installs,retrieval_status,first_seen_at,last_seen_at,updated_at)
 select id,source,skill_name,case when source like '%/%' then split_part(source,'/',1) end,case when source like '%/%' then split_part(source,'/',2) end,'https://skills.sh/'||id,case when source like '%/%' then 'https://github.com/'||source end,installs,'pending',now(),now(),now() from d
 on conflict(id) do update set installs=greatest(coalesce(skillset.skills.installs,0),excluded.installs),last_seen_at=now(),updated_at=now();get diagnostics v_count=row_count;
 insert into skillset.repositories(source,owner,repo) select distinct r->>'source',split_part(r->>'source','/',1),split_part(r->>'source','/',2) from jsonb_array_elements(p_rows) r where coalesce(r->>'source','') like '%/%' on conflict(source) do nothing;
 insert into skillset.owner_search(owner) select distinct split_part(r->>'source','/',1) from jsonb_array_elements(p_rows) r where coalesce(r->>'source','') like '%/%' on conflict(owner) do nothing;return v_count;end;$function$;

create or replace function public.skillset_sync_owner_queue()
returns integer language plpgsql security definer set search_path to 'skillset','public' as $function$
declare v_count integer;begin insert into skillset.owner_search(owner) select distinct owner from skillset.repositories where owner is not null and owner<>'' on conflict(owner) do nothing;get diagnostics v_count=row_count;return v_count;end;$function$;

create or replace function public.skillset_trigger_storage_migration()
returns bigint language plpgsql security definer set search_path to 'public','skillset','extensions' as $function$
declare v_token uuid:=gen_random_uuid();v_request_id bigint;begin insert into skillset.job_tokens(token,purpose,expires_at) values(v_token,'migrate-storage',now()+interval '10 minutes');select net.http_post(url:='https://elnsqdpbxjcrudvwdzbs.supabase.co/functions/v1/skillset-migrate-storage',headers:=jsonb_build_object('Content-Type','application/json'),body:=jsonb_build_object('token',v_token::text,'limit',200)) into v_request_id;return v_request_id;end;$function$;
create or replace function public.skillset_trigger_content_batch()
returns bigint language plpgsql security definer set search_path to 'public','skillset','extensions' as $function$
declare v_token uuid:=gen_random_uuid();v_request_id bigint;begin if not public.skillset_storage_has_capacity() then return 0;end if;insert into skillset.job_tokens(token,purpose,expires_at) values(v_token,'content-batch',now()+interval '10 minutes');select net.http_post(url:='https://elnsqdpbxjcrudvwdzbs.supabase.co/functions/v1/skillset-content-batch',headers:=jsonb_build_object('Content-Type','application/json'),body:=jsonb_build_object('token',v_token::text,'limit',20)) into v_request_id;return v_request_id;end;$function$;
create or replace function public.skillset_trigger_repo_discovery()
returns bigint language plpgsql security definer set search_path to 'public','skillset','extensions' as $function$
declare v_token uuid:=gen_random_uuid();v_request_id bigint;begin if not public.skillset_storage_has_capacity() then return 0;end if;insert into skillset.job_tokens(token,purpose,expires_at) values(v_token,'repo-discovery',now()+interval '10 minutes');select net.http_post(url:='https://elnsqdpbxjcrudvwdzbs.supabase.co/functions/v1/skillset-repo-discovery',headers:=jsonb_build_object('Content-Type','application/json'),body:=jsonb_build_object('token',v_token::text)) into v_request_id;return v_request_id;end;$function$;
create or replace function public.skillset_trigger_leaderboard_seed()
returns bigint language plpgsql security definer set search_path to 'public','skillset','extensions' as $function$
declare v_token uuid:=gen_random_uuid();v_request_id bigint;v_status text;begin select value->>'status' into v_status from skillset.crawl_state where key='leaderboard:all-time';if v_status='complete' then return 0;end if;insert into skillset.job_tokens(token,purpose,expires_at) values(v_token,'leaderboard-seed',now()+interval '10 minutes');select net.http_post(url:='https://elnsqdpbxjcrudvwdzbs.supabase.co/functions/v1/skillset-leaderboard-seed',headers:=jsonb_build_object('Content-Type','application/json'),body:=jsonb_build_object('token',v_token::text)) into v_request_id;return v_request_id;end;$function$;
create or replace function public.skillset_trigger_owner_search()
returns bigint language plpgsql security definer set search_path to 'public','skillset','extensions' as $function$
declare v_token uuid:=gen_random_uuid();v_request_id bigint;begin insert into skillset.job_tokens(token,purpose,expires_at) values(v_token,'owner-search',now()+interval '10 minutes');select net.http_post(url:='https://elnsqdpbxjcrudvwdzbs.supabase.co/functions/v1/skillset-owner-search',headers:=jsonb_build_object('Content-Type','application/json'),body:=jsonb_build_object('token',v_token::text)) into v_request_id;return v_request_id;end;$function$;
